// lib/skill-icons.ts
// لیست **کامل‌ترین و به‌روزترین** آیکون‌های مهارت‌ها از skillicons.dev (تا تاریخ December 2025)
// این لیست بر اساس تمام آیکون‌های موجود در ریپازیتوری اصلی tandpfun/skill-icons استخراج شده و بسیار کامل‌تر از لیست قبلی است.
// نام‌های داخل SKILL_ICONS دقیقاً کلیدهایی هستند که در ادمین پنل، دیتابیس یا کامپوننت‌ها استفاده می‌کنید.
// اگر برنامه‌نویس چیزی تایپ کرد و آیکون وجود داشت، با این لیست autocomplete کامل و دقیق خواهد داشت.

export const SKILL_ICONS = [
  "tools",
  "ableton",
  "activitypub",
  "actix",
  "adonis",
  "ae",
  "aiscript",
  "alpinejs",
  "anaconda",
  "androidstudio",
  "angular",
  "ansible",
  "apollo",
  "apple",
  "appwrite",
  "arch",
  "arduino",
  "astro",
  "atom",
  "au",
  "autocad",
  "aws",
  "azul",
  "azure",
  "babel",
  "bash",
  "bevy",
  "bitbucket",
  "blender",
  "bootstrap",
  "bsd",
  "bun",
  "c",
  "cs",
  "cpp",
  "crystal",
  "cassandra",
  "clion",
  "clojure",
  "cloudflare",
  "cmake",
  "codepen",
  "coffeescript",
  "css",
  "cypress",
  "d3",
  "dart",
  "debian",
  "deno",
  "devto",
  "discord",
  "bots",
  "discordjs",
  "django",
  "docker",
  "dotnet",
  "dynamodb",
  "eclipse",
  "elasticsearch",
  "electron",
  "elixir",
  "elysia",
  "emacs",
  "ember",
  "emotion",
  "express",
  "fastapi",
  "fediverse",
  "figma",
  "firebase",
  "flask",
  "flutter",
  "forth",
  "fortran",
  "gamemakerstudio",
  "gatsby",
  "gcp",
  "git",
  "github",
  "githubactions",
  "gitlab",
  "gmail",
  "gherkin",
  "go",
  "gradle",
  "godot",
  "grafana",
  "graphql",
  "gtk",
  "gulp",
  "haskell",
  "haxe",
  "haxeflixel",
  "heroku",
  "hibernate",
  "html",
  "htmx",
  "idea",
  "ai",
  "instagram",
  "ipfs",
  "java",
  "js",
  "jenkins",
  "jest",
  "jquery",
  "kafka",
  "kali",
  "kotlin",
  "ktor",
  "kubernetes",
  "laravel",
  "latex",
  "less",
  "linkedin",
  "linux",
  "lit",
  "lua",
  "md",
  "mastodon",
  "materialui",
  "matlab",
  "maven",
  "mint",
  "misskey",
  "mongodb",
  "mysql",
  "neovim",
  "nestjs",
  "netlify",
  "nextjs",
  "nginx",
  "nim",
  "nix",
  "nodejs",
  "notion",
  "npm",
  "nuxtjs",
  "obsidian",
  "ocaml",
  "octave",
  "opencv",
  "openshift",
  "openstack",
  "p5js",
  "perl",
  "ps",
  "php",
  "phpstorm",
  "pinia",
  "pkl",
  "plan9",
  "planetscale",
  "pnpm",
  "postgres",
  "postman",
  "powershell",
  "pr",
  "prisma",
  "processing",
  "prometheus",
  "pug",
  "pycharm",
  "py",
  "pytorch",
  "qt",
  "r",
  "rabbitmq",
  "rails",
  "raspberrypi",
  "react",
  "reactivex",
  "redhat",
  "redis",
  "redux",
  "regex",
  "remix",
  "replit",
  "rider",
  "robloxstudio",
  "rocket",
  "rollupjs",
  "ros",
  "ruby",
  "rust",
  "sass",
  "spring",
  "sqlite",
  "stackoverflow",
  "styledcomponents",
  "sublime",
  "supabase",
  "scala",
  "sklearn",
  "selenium",
  "sentry",
  "sequelize",
  "sketchup",
  "solidity",
  "solidjs",
  "svelte",
  "svg",
  "swift",
  "symfony",
  "tailwind",
  "tauri",
  "tensorflow",
  "terraform",
  "threejs",
  "twitter",
  "ts",
  "ubuntu",
  "unity",
  "unreal",
  "v",
  "vala",
  "vercel",
  "vim",
  "visualstudio",
  "vite",
  "vitest",
  "vscode",
  "vscodium",
  "vue",
  "vuetify",
  "wasm",
  "webflow",
  "webpack",
  "webstorm",
  "windicss",
  "windows",
  "wordpress",
  "workers",
  "xd",
  "yarn",
  "yew",
  "zig",
] as const;

export type SkillIconName = (typeof SKILL_ICONS)[number];

// نام‌های خوانا (به فارسی/انگلیسی) برای نمایش در ادمین پنل، صفحه مهارت‌ها و ...
export const ICON_DISPLAY_NAME: Record<SkillIconName, string> = {
  tools: "هیچ / پیش‌فرض", // ← نام فارسی برای نمایش در ادمین
  ableton: "Ableton",
  activitypub: "ActivityPub",
  actix: "Actix",
  adonis: "AdonisJS",
  ae: "After Effects",
  aiscript: "AiScript",
  alpinejs: "Alpine.js",
  anaconda: "Anaconda",
  androidstudio: "Android Studio",
  angular: "Angular",
  ansible: "Ansible",
  apollo: "Apollo",
  apple: "Apple",
  appwrite: "Appwrite",
  arch: "Arch Linux",
  arduino: "Arduino",
  astro: "Astro",
  atom: "Atom",
  au: "Audition",
  autocad: "AutoCAD",
  aws: "AWS",
  azul: "Azul",
  azure: "Azure",
  babel: "Babel",
  bash: "Bash",
  bevy: "Bevy",
  bitbucket: "Bitbucket",
  blender: "Blender",
  bootstrap: "Bootstrap",
  bsd: "BSD",
  bun: "Bun",
  c: "C",
  cs: "C#",
  cpp: "C++",
  crystal: "Crystal",
  cassandra: "Cassandra",
  clion: "CLion",
  clojure: "Clojure",
  cloudflare: "Cloudflare",
  cmake: "CMake",
  codepen: "CodePen",
  coffeescript: "CoffeeScript",
  css: "CSS",
  cypress: "Cypress",
  d3: "D3.js",
  dart: "Dart",
  debian: "Debian",
  deno: "Deno",
  devto: "Dev.to",
  discord: "Discord",
  bots: "Discord Bots",
  discordjs: "Discord.js",
  django: "Django",
  docker: "Docker",
  dotnet: ".NET",
  dynamodb: "DynamoDB",
  eclipse: "Eclipse",
  elasticsearch: "Elasticsearch",
  electron: "Electron",
  elixir: "Elixir",
  elysia: "Elysia",
  emacs: "Emacs",
  ember: "Ember",
  emotion: "Emotion",
  express: "Express",
  fastapi: "FastAPI",
  fediverse: "Fediverse",
  figma: "Figma",
  firebase: "Firebase",
  flask: "Flask",
  flutter: "Flutter",
  forth: "Forth",
  fortran: "Fortran",
  gamemakerstudio: "GameMaker Studio",
  gatsby: "Gatsby",
  gcp: "Google Cloud",
  git: "Git",
  github: "GitHub",
  githubactions: "GitHub Actions",
  gitlab: "GitLab",
  gmail: "Gmail",
  gherkin: "Gherkin",
  go: "Go",
  gradle: "Gradle",
  godot: "Godot",
  grafana: "Grafana",
  graphql: "GraphQL",
  gtk: "GTK",
  gulp: "Gulp",
  haskell: "Haskell",
  haxe: "Haxe",
  haxeflixel: "HaxeFlixel",
  heroku: "Heroku",
  hibernate: "Hibernate",
  html: "HTML",
  htmx: "HTMX",
  idea: "IntelliJ IDEA",
  ai: "Illustrator",
  instagram: "Instagram",
  ipfs: "IPFS",
  java: "Java",
  js: "JavaScript",
  jenkins: "Jenkins",
  jest: "Jest",
  jquery: "jQuery",
  kafka: "Kafka",
  kali: "Kali Linux",
  kotlin: "Kotlin",
  ktor: "Ktor",
  kubernetes: "Kubernetes",
  laravel: "Laravel",
  latex: "LaTeX",
  less: "Less",
  linkedin: "LinkedIn",
  linux: "Linux",
  lit: "Lit",
  lua: "Lua",
  md: "Markdown",
  mastodon: "Mastodon",
  materialui: "Material UI",
  matlab: "MATLAB",
  maven: "Maven",
  mint: "Linux Mint",
  misskey: "Misskey",
  mongodb: "MongoDB",
  mysql: "MySQL",
  neovim: "Neovim",
  nestjs: "NestJS",
  netlify: "Netlify",
  nextjs: "Next.js",
  nginx: "Nginx",
  nim: "Nim",
  nix: "Nix",
  nodejs: "Node.js",
  notion: "Notion",
  npm: "npm",
  nuxtjs: "Nuxt.js",
  obsidian: "Obsidian",
  ocaml: "OCaml",
  octave: "Octave",
  opencv: "OpenCV",
  openshift: "OpenShift",
  openstack: "OpenStack",
  p5js: "p5.js",
  perl: "Perl",
  ps: "Photoshop",
  php: "PHP",
  phpstorm: "PhpStorm",
  pinia: "Pinia",
  pkl: "Pkl",
  plan9: "Plan 9",
  planetscale: "PlanetScale",
  pnpm: "pnpm",
  postgres: "PostgreSQL",
  postman: "Postman",
  powershell: "PowerShell",
  pr: "Premiere Pro",
  prisma: "Prisma",
  processing: "Processing",
  prometheus: "Prometheus",
  pug: "Pug",
  pycharm: "PyCharm",
  py: "Python",
  pytorch: "PyTorch",
  qt: "Qt",
  r: "R",
  rabbitmq: "RabbitMQ",
  rails: "Ruby on Rails",
  raspberrypi: "Raspberry Pi",
  react: "React",
  reactivex: "ReactiveX",
  redhat: "Red Hat",
  redis: "Redis",
  redux: "Redux",
  regex: "Regex",
  remix: "Remix",
  replit: "Replit",
  rider: "Rider",
  robloxstudio: "Roblox Studio",
  rocket: "Rocket",
  rollupjs: "Rollup",
  ros: "ROS",
  ruby: "Ruby",
  rust: "Rust",
  sass: "Sass",
  spring: "Spring",
  sqlite: "SQLite",
  stackoverflow: "Stack Overflow",
  styledcomponents: "styled-components",
  sublime: "Sublime Text",
  supabase: "Supabase",
  scala: "Scala",
  sklearn: "Scikit-learn",
  selenium: "Selenium",
  sentry: "Sentry",
  sequelize: "Sequelize",
  sketchup: "SketchUp",
  solidity: "Solidity",
  solidjs: "SolidJS",
  svelte: "Svelte",
  svg: "SVG",
  swift: "Swift",
  symfony: "Symfony",
  tailwind: "Tailwind CSS",
  tauri: "Tauri",
  tensorflow: "TensorFlow",
  terraform: "Terraform",
  threejs: "Three.js",
  twitter: "Twitter",
  ts: "TypeScript",
  ubuntu: "Ubuntu",
  unity: "Unity",
  unreal: "Unreal Engine",
  v: "V",
  vala: "Vala",
  vercel: "Vercel",
  vim: "Vim",
  visualstudio: "Visual Studio",
  vite: "Vite",
  vitest: "Vitest",
  vscode: "VS Code",
  vscodium: "VSCodium",
  vue: "Vue.js",
  vuetify: "Vuetify",
  wasm: "WebAssembly",
  webflow: "Webflow",
  webpack: "Webpack",
  webstorm: "WebStorm",
  windicss: "WindiCSS",
  windows: "Windows",
  wordpress: "WordPress",
  workers: "Cloudflare Workers",
  xd: "Adobe XD",
  yarn: "Yarn",
  yew: "Yew",
  zig: "Zig",
} as const;

// مپینگ به نام‌های واقعی که skillicons.dev قبول می‌کنه (icon ID واقعی)
export const SKILL_ICON_MAPPING: Record<SkillIconName, string> = {
  tools: "tools",
  ableton: "ableton",
  activitypub: "activitypub",
  actix: "actix",
  adonis: "adonis",
  ae: "ae",
  aiscript: "aiscript",
  alpinejs: "alpinejs",
  anaconda: "anaconda",
  androidstudio: "androidstudio",
  angular: "angular",
  ansible: "ansible",
  apollo: "apollo",
  apple: "apple",
  appwrite: "appwrite",
  arch: "arch",
  arduino: "arduino",
  astro: "astro",
  atom: "atom",
  au: "au",
  autocad: "autocad",
  aws: "aws",
  azul: "azul",
  azure: "azure",
  babel: "babel",
  bash: "bash",
  bevy: "bevy",
  bitbucket: "bitbucket",
  blender: "blender",
  bootstrap: "bootstrap",
  bsd: "bsd",
  bun: "bun",
  c: "c",
  cs: "cs",
  cpp: "cpp",
  crystal: "crystal",
  cassandra: "cassandra",
  clion: "clion",
  clojure: "clojure",
  cloudflare: "cloudflare",
  cmake: "cmake",
  codepen: "codepen",
  coffeescript: "coffeescript",
  css: "css",
  cypress: "cypress",
  d3: "d3",
  dart: "dart",
  debian: "debian",
  deno: "deno",
  devto: "devto",
  discord: "discord",
  bots: "bots",
  discordjs: "discordjs",
  django: "django",
  docker: "docker",
  dotnet: "dotnet",
  dynamodb: "dynamodb",
  eclipse: "eclipse",
  elasticsearch: "elasticsearch",
  electron: "electron",
  elixir: "elixir",
  elysia: "elysia",
  emacs: "emacs",
  ember: "ember",
  emotion: "emotion",
  express: "express",
  fastapi: "fastapi",
  fediverse: "fediverse",
  figma: "figma",
  firebase: "firebase",
  flask: "flask",
  flutter: "flutter",
  forth: "forth",
  fortran: "fortran",
  gamemakerstudio: "gamemakerstudio",
  gatsby: "gatsby",
  gcp: "gcp",
  git: "git",
  github: "github",
  githubactions: "githubactions",
  gitlab: "gitlab",
  gmail: "gmail",
  gherkin: "gherkin",
  go: "go",
  gradle: "gradle",
  godot: "godot",
  grafana: "grafana",
  graphql: "graphql",
  gtk: "gtk",
  gulp: "gulp",
  haskell: "haskell",
  haxe: "haxe",
  haxeflixel: "haxeflixel",
  heroku: "heroku",
  hibernate: "hibernate",
  html: "html",
  htmx: "htmx",
  idea: "idea",
  ai: "ai",
  instagram: "instagram",
  ipfs: "ipfs",
  java: "java",
  js: "js",
  jenkins: "jenkins",
  jest: "jest",
  jquery: "jquery",
  kafka: "kafka",
  kali: "kali",
  kotlin: "kotlin",
  ktor: "ktor",
  kubernetes: "kubernetes",
  laravel: "laravel",
  latex: "latex",
  less: "less",
  linkedin: "linkedin",
  linux: "linux",
  lit: "lit",
  lua: "lua",
  md: "md",
  mastodon: "mastodon",
  materialui: "materialui",
  matlab: "matlab",
  maven: "maven",
  mint: "mint",
  misskey: "misskey",
  mongodb: "mongodb",
  mysql: "mysql",
  neovim: "neovim",
  nestjs: "nestjs",
  netlify: "netlify",
  nextjs: "nextjs",
  nginx: "nginx",
  nim: "nim",
  nix: "nix",
  nodejs: "nodejs",
  notion: "notion",
  npm: "npm",
  nuxtjs: "nuxtjs",
  obsidian: "obsidian",
  ocaml: "ocaml",
  octave: "octave",
  opencv: "opencv",
  openshift: "openshift",
  openstack: "openstack",
  p5js: "p5js",
  perl: "perl",
  ps: "ps",
  php: "php",
  phpstorm: "phpstorm",
  pinia: "pinia",
  pkl: "pkl",
  plan9: "plan9",
  planetscale: "planetscale",
  pnpm: "pnpm",
  postgres: "postgres",
  postman: "postman",
  powershell: "powershell",
  pr: "pr",
  prisma: "prisma",
  processing: "processing",
  prometheus: "prometheus",
  pug: "pug",
  pycharm: "pycharm",
  py: "py",
  pytorch: "pytorch",
  qt: "qt",
  r: "r",
  rabbitmq: "rabbitmq",
  rails: "rails",
  raspberrypi: "raspberrypi",
  react: "react",
  reactivex: "reactivex",
  redhat: "redhat",
  redis: "redis",
  redux: "redux",
  regex: "regex",
  remix: "remix",
  replit: "replit",
  rider: "rider",
  robloxstudio: "robloxstudio",
  rocket: "rocket",
  rollupjs: "rollupjs",
  ros: "ros",
  ruby: "ruby",
  rust: "rust",
  sass: "sass",
  spring: "spring",
  sqlite: "sqlite",
  stackoverflow: "stackoverflow",
  styledcomponents: "styledcomponents",
  sublime: "sublime",
  supabase: "supabase",
  scala: "scala",
  sklearn: "sklearn",
  selenium: "selenium",
  sentry: "sentry",
  sequelize: "sequelize",
  sketchup: "sketchup",
  solidity: "solidity",
  solidjs: "solidjs",
  svelte: "svelte",
  svg: "svg",
  swift: "swift",
  symfony: "symfony",
  tailwind: "tailwind",
  tauri: "tauri",
  tensorflow: "tensorflow",
  terraform: "terraform",
  threejs: "threejs",
  twitter: "twitter",
  ts: "ts",
  ubuntu: "ubuntu",
  unity: "unity",
  unreal: "unreal",
  v: "v",
  vala: "vala",
  vercel: "vercel",
  vim: "vim",
  visualstudio: "visualstudio",
  vite: "vite",
  vitest: "vitest",
  vscode: "vscode",
  vscodium: "vscodium",
  vue: "vue",
  vuetify: "vuetify",
  wasm: "wasm",
  webflow: "webflow",
  webpack: "webpack",
  webstorm: "webstorm",
  windicss: "windicss",
  windows: "windows",
  wordpress: "wordpress",
  workers: "workers",
  xd: "xd",
  yarn: "yarn",
  yew: "yew",
  zig: "zig",
} as const;
