// lib/skill-icons.ts
// لیست کامل آیکون‌های مهارت‌ها - نام دقیق رو تو Select یا کارت‌ها استفاده کن

export const SKILL_ICONS = [
  "html5",
  "css3",
  "javascript",
  "typescript",
  "react",
  "nextjs",
  "vuejs",
  "nuxtjs",
  "angular",
  "svelte",
  "gatsby",
  "redux",
  "tailwindcss",
  "bootstrap",
  "materialui",
  "chakraui",
  "antd",
  "framer-motion",

  "nodejs",
  "express",
  "nest",
  "fastify",
  "koa",
  "hapi",
  "socketio",

  "mongodb",
  "mysql",
  "postgresql",
  "sqlite",
  "prisma",
  "redis",
  "firebase",
  "supabase",

  "git",
  "github",
  "gitlab",
  "bitbucket",
  "docker",
  "kubernetes",
  "jenkins",
  "aws",
  "azure",
  "gcp",
  "vercel",
  "netlify",
  "heroku",
  "digitalocean",

  "figma",
  "adobexd",
  "sketch",
  "photoshop",
  "illustrator",

  "vscode",
  "vim",
  "neovim",
  "webstorm",
  "intellij",
  "phpstorm",

  "linux",
  "bash",
  "powershell",

  "graphql",
  "apollo",
  "trpc",

  "jest",
  "cypress",
  "testinglibrary",
  "playwright",

  "webpack",
  "vite",
  "rollup",
  "esbuild",
  "parcel",

  "python",
  "django",
  "flask",
  "fastapi",
  "numpy",
  "pandas",

  "java",
  "spring",
  "kotlin",
  "android",

  "swift",
  "ios",

  "csharp",
  "dotnet",

  "go",
  "rust",
  "php",
  "laravel",
  "symfony",

  "ruby",
  "rails",

  "elixir",
  "phoenix",

  "flutter",
  "dart",

  "electron",
  "tauri",

  "threejs",
  "babylonjs",

  "unity",
  "unreal",

  // اضافه‌های بیشتر در صورت نیاز
  "sass",
  "less",
  "styledcomponents",
  "emotion",
  "jquery",
  "d3js",
  "chartjs",
  "tensorflow",
  "pytorch",
  "opencv",
  "selenium",
  "postman",
  "insomnia",
  "nginx",
  "apache",
  "cloudflare",
  "bun",
  "deno",
] as const;

// نوع برای تایپ‌سیف بودن در Select و غیره
export type SkillIconName = typeof SKILL_ICONS[number];

// اگر از lucide-react استفاده می‌کنی، می‌تونی این مپ رو هم داشته باشی (اختیاری)
export const ICON_DISPLAY_NAME: Record<SkillIconName, string> = {
  html5: "HTML5",
  css3: "CSS3",
  javascript: "JavaScript",
  typescript: "TypeScript",
  react: "React",
  nextjs: "Next.js",
  vuejs: "Vue.js",
  nuxtjs: "Nuxt.js",
  angular: "Angular",
  svelte: "Svelte",
  gatsby: "Gatsby",
  redux: "Redux",
  tailwindcss: "Tailwind CSS",
  bootstrap: "Bootstrap",
  materialui: "Material UI",
  chakraui: "Chakra UI",
  antd: "Ant Design",
  "framer-motion": "Framer Motion",

  nodejs: "Node.js",
  express: "Express",
  nest: "NestJS",
  fastify: "Fastify",
  koa: "Koa",
  hapi: "Hapi",
  socketio: "Socket.io",

  mongodb: "MongoDB",
  mysql: "MySQL",
  postgresql: "PostgreSQL",
  sqlite: "SQLite",
  prisma: "Prisma",
  redis: "Redis",
  firebase: "Firebase",
  supabase: "Supabase",

  git: "Git",
  github: "GitHub",
  gitlab: "GitLab",
  bitbucket: "Bitbucket",
  docker: "Docker",
  kubernetes: "Kubernetes",
  jenkins: "Jenkins",
  aws: "AWS",
  azure: "Azure",
  gcp: "Google Cloud",
  vercel: "Vercel",
  netlify: "Netlify",
  heroku: "Heroku",
  digitalocean: "DigitalOcean",

  figma: "Figma",
  adobexd: "Adobe XD",
  sketch: "Sketch",
  photoshop: "Photoshop",
  illustrator: "Illustrator",

  vscode: "VS Code",
  vim: "Vim",
  neovim: "Neovim",
  webstorm: "WebStorm",
  intellij: "IntelliJ",
  phpstorm: "PhpStorm",

  linux: "Linux",
  bash: "Bash",
  powershell: "PowerShell",

  graphql: "GraphQL",
  apollo: "Apollo",
  trpc: "tRPC",

  jest: "Jest",
  cypress: "Cypress",
  testinglibrary: "Testing Library",
  playwright: "Playwright",

  webpack: "Webpack",
  vite: "Vite",
  rollup: "Rollup",
  esbuild: "esbuild",
  parcel: "Parcel",

  python: "Python",
  django: "Django",
  flask: "Flask",
  fastapi: "FastAPI",
  numpy: "NumPy",
  pandas: "Pandas",

  java: "Java",
  spring: "Spring",
  kotlin: "Kotlin",
  android: "Android",

  swift: "Swift",
  ios: "iOS",

  csharp: "C#",
  dotnet: ".NET",

  go: "Go",
  rust: "Rust",
  php: "PHP",
  laravel: "Laravel",
  symfony: "Symfony",

  ruby: "Ruby",
  rails: "Ruby on Rails",

  elixir: "Elixir",
  phoenix: "Phoenix",

  flutter: "Flutter",
  dart: "Dart",

  electron: "Electron",
  tauri: "Tauri",

  threejs: "Three.js",
  babylonjs: "Babylon.js",

  unity: "Unity",
  unreal: "Unreal Engine",

  sass: "Sass",
  less: "Less",
  styledcomponents: "styled-components",
  emotion: "Emotion",
  jquery: "jQuery",
  d3js: "D3.js",
  chartjs: "Chart.js",
  tensorflow: "TensorFlow",
  pytorch: "PyTorch",
  opencv: "OpenCV",
  selenium: "Selenium",
  postman: "Postman",
  insomnia: "Insomnia",
  nginx: "Nginx",
  apache: "Apache",
  cloudflare: "Cloudflare",
  bun: "Bun",
  deno: "Deno",
} as const;